### ISSUE TITLE
How to get overlay

### ISSUE THREAD

**Issue by elegantcoin** [robertosannazzaro/motion-heatmap-opencv#1]
The output.avi has some kind of "green" mask on it, I wonder to know how to get the real heatmap.

**Comment by robsannaa** [comment]
谢谢 for pointing it out! I noticed I was applying a wrong colormap, instead  of `cv2.COLORMAP_HOT` I was using `cv2.COLORMAP_SUMMER`, I pushed the changes, try now and let me know please!

**Comment by elegantcoin** [comment]
> 谢谢 for pointing it out! I noticed I was applying a wrong colormap, instead of `cv2.COLORMAP_HOT` I was using `cv2.COLORMAP_SUMMER`, I pushed the changes, try now and let me know please!

Thank you!

**Comment by elegantcoin** [comment]
Maybe I want to add descriptive label ("a hat") on the moving object.

**Comment by neuropil** [comment]
I'm still getting a green tinge to my saved video, which makes it hard to see the heat-map.

**Comment by robsannaa** [comment]
Please, refer to the issue pointed here by elegantcoin, you can change line 41 in `motion_heatmap.py`
change the colormap to `cv2.COLORMAP_HOT` instead of `cv2.COLORMAP_SUMMER`.
https://github.com/robertosannazzaro/motion-heatmap-opencv/blob/248bb153ac70c51b3669095e6b6ea0b567f5cb60/motion_heatmap.py#L41
